name: Build, Test, Push Docker

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build/Test/Push Image
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Update Version
        run: |
          cd ${{ github.workspace }}/src/server
          npx semantic-release
          export VTAG=$(cat ./package.json | jq --raw-output .version)
          echo "::set-env name=VTAG::$VTAG"

      - name: Test Container
        run: |
          cd ${{ github.workspace }}/src/test/cypress/e2e
          docker-compose up --exit-code-from cypress

      - name: Build Container
        run: |
          echo $VTAG
          docker build -t blockappsserver .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Tag and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: blockappsserver
          IMAGE_TAG: PROD
        run: |
          docker tag blockappsserver $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
