name: On Pull Request Test

on:
  pull_request:
    types:
      - opened
jobs:
  test_docker:
    name: Test Image
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Build React App
        run: |
          cd ${{ github.workspace }}/src/client
          npm run build

      - name: Test Container
        run: |
          cd ${{ github.workspace }}/src/test/cypress/e2e
          docker-compose up --exit-code-from cypress
